spring.application.name=Finance

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.expiration=86400000
token.signing.key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
